### PR TITLE
A small fix to Readme

### PR DESCRIPTION
**Pull request by palmiak**
The `wp-cli` part isn't nessesary.

### CODE REVIEW

**Comment by darrenjacoby** [comment]
It is if you're not using the -p version

**Comment by palmiak** [comment]
I checked it `-p` instals as package but the plugin edition installs as 'mu-plugin' so it's always activated - https://screenshots.firefox.com/YmeLLaT5BYHybNVx/localhost 

I've also fixed composer require versions

**Comment by darrenjacoby** [comment]
I've merged this. 

It appears, according to Packagist, that models is used equally as a bedrock dep, and sage dep. I would be open to a better versioning scheme if users feel one exists.

**Comment by palmiak** [comment]
@darrenjacoby maybe it would be better to seperate them to separate repos - `models-plugin` and `models-package`. This repo would stay for backward compatibility. What do you think?

**Pull request merged**
